### ISSUE TITLE
debug单个模型的方法

### ISSUE THREAD

**Issue by guochaorong** [PaddlePaddle/paddle-ce-latest-kpis#130]
![ggg](https://user-images.githubusercontent.com/32069604/44065744-02c2cb78-9f9f-11e8-917b-b5385b8e61a2.png)

最下面一个是正确的， 最上面是错误的，
出问题的应该在这些之间，

排查方法：
![ggg](https://user-images.githubusercontent.com/32069604/44065790-59430814-9f9f-11e8-98f7-f1123a02f0c5.png)

![kkk](https://user-images.githubusercontent.com/32069604/44065870-e07a9590-9f9f-11e8-9cdd-51149c1eb395.png)

**Comment by tensor-tang** [comment]
fixed by https://github.com/PaddlePaddle/Paddle/pull/12681
