### ISSUE TITLE
Model stability analysis

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/paddle-ce-latest-kpis#21]
Environment：Tesla V100 cuda version：384.81

We run each model ten times and get the follow data.
resnet50:

kpi | min | max | mean | median | std | （std/mean）*100%
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
cifar10_128_gpu_memory | 1566 | 1596 | 1589.6 | 1596 | 10 | 0.6%
cifar10_128_train_acc | 0.966 | 0.998 | 0.985 | 0.990 | 0.011 | 1.1%
cifar10_128_train_speed | 346.3 | 406.1 | 373.0 | 370.7 | 19.7 | 5.2%
flowers_64_gpu_memory | 10680 | 12848 | 12139 | 12459 | 779.9 | 6.4%
flowers_64_train_speed | 70.3 | 76.3 | 74.1 | 74.9 | 2.14 | 2.8%

resnet30

kpi | min | max | mean | median | std | （std/mean）*100%
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
train_cost | 2.32 | 2.69 | 2.51 | 2.51 | 0.096 | 3.8%
train_duration | 10.24 | 10.65 | 10.366 | 10.347 | 0.101 | 0.9%

minst

kpi | min | max | mean | median | std | （std/mean）*100%
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
test_acc | 0.9858 | 0.9890 | 0.9877 | 0.9876 | 0.0010 | 0.1%
train_acc | 0.9919 | 0.9933 | 0.9929 | 0.9929 | 0.0003 | 0.03%
train_duration | 37.6037 | 38.7788 | 38.2673 | 38.5541 | 0.4592 | 1.2%

**Comment by kolinwei** [comment]
Environment：Tesla P40 cuda version：384.66

resnet50:

kpi | min | max | mean | median | std | （std/mean）*100%
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
cifar10_128_gpu_memory | 923 | 953 | 950 | 953 | 9 | 0.947%
cifar10_128_train_acc | 0.960 | 0.999 | 0.9837 | 0.9847 | 0.011 | 1.2%
cifar10_128_train_speed | 548.5 | 559.5 | 553.6 | 553.5 | 3.519 | 0.635%
flowers_64_gpu_memory | 5037 | 5541 | 5330 | 5441 | 189.98 | 3.564%
flowers_64_train_speed | 52.59 | 53.57 | 53.23 | 53.33 | 0.286 | 0.537%

resnet30

kpi | min | max | mean | median | std | （std/mean）*100%
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
train_cost | 2.41 | 2.58 | 2.51 | 2.52 | 0.051 | 2.0%
train_duration | 34.52 | 36.23 | 34.74 | 34.57 | 0.498 | 1.43%

minst

kpi | min | max | mean | median | std | （std/mean）*100%
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
test_acc | 0.9853 | 0.9884 | 0.9873 | 0.9874 | 0.0009 | 0.09%
train_acc | 0.9925 | 0.9934 | 0.9930 | 0.9931 | 0.0003 | 0.03%
train_duration | 54.05 | 54.69 | 54.36 | 54.34 | 0.022 | 0.4%

LSTM

kpi | min | max | mean | median | std | （std/mean）*100%
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
imdb_32_train_speed | 538.029 | 639.594 | 583.233 | 582.637 | 29.726 | 5.1%
imdb_32_gpu_memory | 443 | 475 | 459 | 461 | 8.78 | 1.9%

VGG16

kpi | min | max | mean | median | std | （std/mean）*100%
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
cifar10_128_train_speed | 512.9 | 530.4 | 524.3 | 525.2 | 5.73 | 1.1%
cifar10_128_gpu_memory | 1185 | 1185 | 1185 | 1185 | 0 | 0.0%
flowers_32_train_speed | 26.26 | 26.76 | 26.56 | 26.60 | 0.183 | 0.68%

Seq2Seq

kpi | min | max | mean | median | std | （std/mean）*100%
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
wmb_128_train_speed | 2685.27 | 2772.89 | 2724.99 | 2729.39 | 26.84 | 0.98%
wmb_128_gpu_memory | 1703 | 1893 | 1804 | 1794 | 60.56 | 3.3%

**Comment by Superjomn** [comment]
If we limit the `std/mean` threshold to 2%, it seems that most factors are not stable. So can we withdraw the unstable tasks first, and add them later after some fix.
