### ISSUE TITLE
lstm memory kpi 超阈值

### ISSUE THREAD

**Issue by guochaorong** [PaddlePaddle/paddle-ce-latest-kpis#41]
http://18.222.34.7:8080/viewLog.html?buildId=742&buildTypeId=Paddle_ContinuousEvaluation

![mem](https://user-images.githubusercontent.com/32069604/41345959-b2ed60f0-6f37-11e8-9a69-c5ff17a3a70c.PNG)

**Comment by Yancey1989** [comment]
看起来在后面的几轮测试中并没有复现超出阈值的情况，看起来像是LSTM的模型有一定随机性导致的。
例如：http://ce.paddlepaddle.org/commit/details?commit=7c426be98c6680bbcd0684ebc62244ec2f53183c

**Comment by kuke** [comment]
Thanks to @Yancey1989 , 我觉得可以等等看

**Comment by guochaorong** [comment]
恩啊 ， 关于CE模型的不同kpi指标的阈值， 近期一起讨论定下~

**Comment by kolinwei** [comment]
__
