### ISSUE TITLE
mnist训练时长超出阈值

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/paddle-ce-latest-kpis#42]
http://18.222.34.7:8080/viewLog.html?buildId=748&buildTypeId=Paddle_ContinuousEvaluation&tab=buildChangesDiv

<img width="1050" alt="2018-06-13 8 11 32" src="https://user-images.githubusercontent.com/3064195/41350542-154551a0-6f46-11e8-83b2-3832a916b013.png">

**Comment by Superjomn** [comment]
这个应该找让这个模型失败的pr的作者，不是找模型的作者啊

**Comment by Superjomn** [comment]
那个是否是有人在 AWS 机器上起了任务？ 如果后面一个 task 又正常了的话

**Comment by kuke** [comment]
目前的观察是有些错误是偶发性的，我建议让子弹飞一会儿
