### ISSUE TITLE
image_classification模型 acc 指标固定不下来

### ISSUE THREAD

**Issue by guochaorong** [PaddlePaddle/paddle-ce-latest-kpis#70]
该模型已经去掉shuffle，并设置了seed。 每次跑下来acc 指标0.05左右浮动

http://ce.paddlepaddle.org/commit/draw_scalar?task=image_classification

![333](https://user-images.githubusercontent.com/32069604/41907430-6bab9626-7973-11e8-99c4-bcb395e01983.PNG)

CE中已经close该kpi指标，https://github.com/PaddlePaddle/paddle-ce-latest-kpis/pull/69/files

 请青青老师调查并open该指标。

**Comment by Superjomn** [comment]
是seed 的问题？

**Comment by panyx0718** [comment]
![image](https://user-images.githubusercontent.com/2887803/43246204-77590454-90e3-11e8-9c10-63b0489f61cf.png)

**Comment by panyx0718** [comment]
感觉是趋势性下滑。。。

**Comment by kolinwei** [comment]
reader.py 里面的THREAD需要设置为1，加上固定seed，这样才能保证每次训练时读入的数据顺序是一致的

**Comment by guochaorong** [comment]
赞，我去改了验证下

**Comment by guochaorong** [comment]
https://github.com/PaddlePaddle/paddle-ce-latest-kpis/pull/107
