### ISSUE TITLE
transformer模型性能下降

### ISSUE THREAD

**Issue by guochaorong** [PaddlePaddle/paddle-ce-latest-kpis#80]
transformer模型各个commit的性能数据：

http://18.222.34.7/commit/draw_scalar?task=transformer
![mm](https://user-images.githubusercontent.com/32069604/42686949-0c9321ea-86ca-11e8-9883-df0b423284c8.JPG)

commit 72ce4d5 和 a376efb 之间的某个pr有问题，
![dd](https://user-images.githubusercontent.com/32069604/42686764-8196ecac-86c9-11e8-9f0a-206288218865.JPG)

revert这个 https://github.com/PaddlePaddle/Paddle/pull/12103 到paddlepaddle repo ce 分支：https://github.com/PaddlePaddle/Paddle/commit/7af363d0a65eee7a12c1bf183dcaf17110c4fe9a

debug发现，性能恢复
http://18.222.34.7:8080/viewLog.html?buildId=1462&buildTypeId=Paddle_ContinuousEvaluationDebug&tab=buildLog
![ss](https://user-images.githubusercontent.com/32069604/42686690-46f2e86c-86c9-11e8-8629-5ba879922220.JPG)

**Comment by jacquesqiao** [comment]
这个问题可能是正常的，我需要分析下，之前是有个bug

**Comment by jacquesqiao** [comment]
初步分析这个现象符合预期，之前的adam optimizer实现有bug，导致所有的parameter共享同一个beta2_pow_acc和beta2_pow_acc，而且每次迭代只会计算一次scale，修复之后，每个参数都有自己的beta2_pow_acc，对应的也会有自己的scale，导致计算的scale变多了

**Comment by guochaorong** [comment]
这里解释了时间为什么变长了
```sh
         for p in parameters:
              self._add_accumulator(self._moment1_acc_str, p)
              self._add_accumulator(self._moment2_acc_str, p)
```
可是没有说明这个fix  的收益是什么？ 
为什么每一个parameter需要自己的 beta1_pow_acc或beta2_pow_acc？这样修改后看起来 train的acc 数据并没有变好，

**Comment by jacquesqiao** [comment]
对于同步而言，两种写法效果是一样的，对于异步，之前的写法是不对的。商量了一下，后面会通过一个pass来把相关的scale op fuse成一个，这样更符合框架的整体设计。
